INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB01', 'QS01', 'AS01')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB01', 'QS02', 'AS05')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB01', 'QS03', 'AS13')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB01', 'QS04', 'AS16')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB01', 'QS05', 'AS21')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB02', 'QS01', 'AS01')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB02', 'QS02', 'AS05')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB02', 'QS03', 'AS13')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB02', 'QS04', 'AS16')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB02', 'QS05', 'AS21')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB03', 'QS01', 'AS01')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB03', 'QS02', 'AS05')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB03', 'QS03', 'AS13')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB03', 'QS04', 'AS16')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB03', 'QS05', 'AS21')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB04', 'QS01', 'AS01')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB04', 'QS02', 'AS05')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB04', 'QS03', 'AS13')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB04', 'QS04', 'AS16')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB04',  'QS05', 'AS21')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB05',  'QS01', 'AS01')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB05', 'QS02', 'AS05')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB05', 'QS03', 'AS13')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB05',  'QS04', 'AS16')
;
INSERT INTO QUESTION_ANSWER(USER_UID, QUESTION_UID, ANSWER_UID)
VALUE ('MB05',  'QS05', 'AS21')
;